// The audit metadata: for every automated email, what fires it and exactly when.
// Every field here was read out of the tree (systemd units, Makefile targets,
// cron cohort SQL, the Stripe webhook switch), not from the prose doc.

export const GROUPS = [
  { id: 'auth', label: 'Account & auth', blurb: 'Fires on an action the person just took. No opt-out — these are transactional.' },
  { id: 'welcome', label: 'Welcome & onboarding', blurb: 'Fires once, off the Stripe subscription lifecycle.' },
  { id: 'trial', label: 'Trial lifecycle', blurb: 'The trial clock. Two sweeps and two webhook bookends.' },
  { id: 'billing', label: 'Billing & dunning', blurb: 'Payment failures, the grace window, and the recovery bookend.' },
  { id: 'nudge', label: 'Conversion nudges', blurb: 'Signed up, never converted. All one-shot, all latched.' },
  { id: 'churn', label: 'Retention & churn', blurb: 'Cancelled or lapsed. Two of the three do NOT auto-send — see the flag.' },
  { id: 'product', label: 'Product alerts', blurb: 'Queue-driven, per-event.' },
  { id: 'operator', label: 'Operator-only', blurb: 'Goes to the founder inbox. No member ever receives these.' },
];

// autoSends: true = a member's inbox receives this with no human in the loop.
//            false = the timer runs but only produces an operator review digest.
export const CATALOG = {
  // ---------------------------------------------------------------- auth ----
  'email-verification': {
    group: 'auth', title: 'Email verification', channel: 'member', autoSends: true,
    trigger: 'App action', triggerDetail: 'core/serverAuth.ts — on registration',
    when: 'Immediately on sign-up, when the account row is created.',
    cadence: 'Once per registration',
    cohort: 'Anyone who registers.',
    latch: 'None — reissued whenever a new verification link is minted.',
    optOut: 'None (transactional)', foh: false,
    source: 'core/mailer.ts:279 · core/serverAuth.ts',
    notes: 'Link expires in 24h. Verification gates checkout, so this is on the critical path to revenue.',
  },
  'password-reset': {
    group: 'auth', title: 'Password reset', channel: 'member', autoSends: true,
    trigger: 'App action', triggerDetail: 'app/api/auth/password/forgot/route.ts',
    when: 'Immediately on a "forgot password" request.',
    cadence: 'Once per request',
    cohort: 'Anyone who submits the forgot-password form.',
    latch: 'None — rate limiting lives in the route, not a DB latch.',
    optOut: 'None (transactional)', foh: false,
    source: 'core/mailer.ts:2860',
    notes: 'Link expires in 30 minutes, single use.',
  },
  'verify-reminder': {
    group: 'nudge', title: 'Verify reminder', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-verify-reminders.timer → make verify-reminders YES=1',
    when: '2–168 hours after registering, if the address was never confirmed. Swept every 2 hours.',
    cadence: 'Timer: 00/2:20 UTC (every 2h, +0–5m jitter)',
    cohort: "tier='public' AND email_verified_at IS NULL AND stripe_subscription_id IS NULL AND verify_reminder_email_sent_at IS NULL AND deleted_at IS NULL AND created_at within [now-168h, now-2h]",
    latch: 'verify_reminder_email_sent_at — permanent one-shot',
    optOut: 'None (account-completion, not marketing)', foh: false,
    source: 'core/mailer.ts:2810 · scripts/send-verify-reminders.mts (LAG 2h / LOOKBACK 7d)',
    notes: 'Mints a fresh 24h verify link at send time so the link in the mail is never already dead.',
  },

  // ------------------------------------------------------------- welcome ----
  'paid-welcome': {
    group: 'welcome', title: 'Trial / paid welcome', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'checkout.session.completed / customer.subscription.created → maybeSendPaidWelcomeEmail',
    when: 'Seconds after checkout completes — as soon as Stripe posts the event.',
    cadence: 'Once per account (first paid checkout)',
    cohort: 'First subscription on the account; not a founding-tier checkout (that branches to the founding welcome).',
    latch: 'paid_welcome_email_sent_at — never cleared',
    optOut: 'None (transactional)', foh: true,
    source: 'core/mailer.ts:374 · app/api/webhooks/stripe/route.ts:1233',
    notes: 'trialDays is measured off the subscription\'s own trial_start→trial_end, not a constant, so a 30-day reactivation trial renders "30-day free trial".',
  },
  'founding-welcome': {
    group: 'welcome', title: 'Founding-member welcome', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'checkout.session.completed → maybeSendPaidWelcomeEmail (founding branch)',
    when: 'Seconds after a founding-tier checkout completes.',
    cadence: 'Once per account',
    cohort: 'Founding-tier checkout only.',
    latch: 'paid_welcome_email_sent_at (shared with the paid welcome)',
    optOut: 'None (transactional)', foh: true,
    source: 'core/mailer.ts:590 · app/api/webhooks/stripe/route.ts:1231',
  },
  'welcome-back': {
    group: 'welcome', title: 'Welcome back (resubscribe)', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'subscription sync → subscription_lapsed 1→0',
    when: 'Seconds after a previously-lapsed account subscribes again.',
    cadence: 'Once per lapse→return cycle (re-arms on each new lapse)',
    cohort: 'subscription_lapsed = 1 at the moment the new subscription syncs active.',
    latch: 'subscription_lapsed flag, cleared to 0 when this fires',
    optOut: 'None (transactional)', foh: true,
    source: 'core/mailer.ts:1315 · app/api/webhooks/stripe/route.ts:1271',
    notes: 'Carries the API-key walkthrough as a repair notice — dropping below Pro revoked every key the account held.',
  },
  'trial-quickstart': {
    group: 'welcome', title: 'Trial quickstart bridge', channel: 'member', autoSends: false,
    trigger: 'Manual', triggerDetail: 'make send-trial-quickstart — no timer',
    when: 'Never automatically. One-shot backfill, run by hand.',
    cadence: 'Manual only',
    cohort: 'Members who were mid-trial before the activation-focused welcome shipped.',
    latch: 'None — the operator picks the recipients',
    optOut: 'n/a', foh: true,
    source: 'core/mailer.ts:510 · scripts/send-trial-quickstart.mts',
    notes: 'Included for completeness: it is wired to a Makefile target but NOT to any systemd timer.',
  },

  // --------------------------------------------------------------- trial ----
  'trial-value-nudge': {
    group: 'trial', title: 'Mid-trial value nudge', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-trial-value-nudge.timer → make trial-value-nudge YES=1',
    when: '120 hours (5 days) BEFORE trial end — i.e. ~day 2 of a 7-day trial. ±3h window, swept every 6 hours.',
    cadence: 'Timer: 00/6:45 UTC (every 6h, +0–5m jitter)',
    cohort: "subscription_status='trialing' AND trial_midpoint_email_sent_at IS NULL AND cancel_at_period_end=0 AND marketing_unsubscribed_at IS NULL AND deleted_at IS NULL AND current_period_end within target ±3h",
    latch: 'trial_midpoint_email_sent_at — permanent one-shot',
    optOut: 'Honors marketing_unsubscribed_at; carries an unsubscribe link', foh: false,
    source: 'core/mailer.ts:946 · scripts/send-trial-value-nudge.mts (TARGET_HOURS 120)',
    notes: 'Deliberately carries NO charge or cancel language — its whole job is time-to-value, ahead of the day 3–7 cancel wave.',
  },
  'trial-reminder': {
    group: 'trial', title: '48h trial-end reminder', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-trial-reminders.timer → make trial-reminders YES=1',
    when: '48 hours BEFORE the trial converts. ±3h window, swept every 6 hours.',
    cadence: 'Timer: 00/6:15 UTC (every 6h, +0–5m jitter)',
    cohort: "subscription_status='trialing' AND trial_reminder_email_sent_at IS NULL AND cancel_at_period_end=0 AND current_period_end within target ±3h",
    latch: 'trial_reminder_email_sent_at — re-arms on each fresh trialing window',
    optOut: 'None (billing notice — sends regardless of marketing opt-out)', foh: false,
    source: 'core/mailer.ts:719 · scripts/send-trial-reminders.mts (TARGET_HOURS 48)',
    notes: 'The charge amount and card are resolved live from Stripe per member at send time. Anyone who already clicked Cancel is excluded — their trial will not convert. Carries NO discount: the 25% is a win-back lever, not something handed to a trialer who is about to convert anyway.',
  },
  'trial-converted': {
    group: 'trial', title: 'Trial conversion confirmation', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'invoice.paid → maybeSendTrialConvertedEmail',
    when: "Seconds after the trial's first real charge clears.",
    cadence: 'Once per account, ever',
    cohort: 'isTrialConversionInvoice: a subscription_cycle invoice created within ~2 days of trial_end.',
    latch: 'trial_converted_email_sent_at — never cleared',
    optOut: 'None (receipt)', foh: true,
    source: 'core/mailer.ts:1853 · app/api/webhooks/stripe/route.ts:1504',
    notes: 'The conversion predicate is what keeps this off ordinary renewals — invoice.paid fires on every cycle.',
  },
  'trial-conversion-failed': {
    group: 'trial', title: 'Trial conversion declined', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'invoice.payment_failed (attempt_count === 1) → trial branch',
    when: 'Seconds after the FIRST failed attempt on the conversion charge. Silent on Stripe Smart Retries.',
    cadence: 'Once per failure episode',
    cohort: 'Same isTrialConversionInvoice predicate as the success bookend.',
    latch: 'invoice.attempt_count === 1 gate (not a DB latch)',
    optOut: 'None (urgent billing)', foh: false,
    source: 'core/mailer.ts:1574 · app/api/webhooks/stripe/route.ts:2318',
  },

  // ------------------------------------------------------------- billing ----
  'payment-failed': {
    group: 'billing', title: 'Payment failed', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'invoice.payment_failed (attempt_count === 1) → renewal branch',
    when: 'Seconds after the FIRST failed renewal attempt. Retries send nothing.',
    cadence: 'Once per failure episode',
    cohort: 'An established (non-trial) renewal invoice that failed on attempt 1.',
    latch: 'invoice.attempt_count === 1 gate',
    optOut: 'None (urgent billing)', foh: false,
    source: 'core/mailer.ts:1459 · app/api/webhooks/stripe/route.ts:2320',
    notes: 'The attempt_count gate is precisely why a second dunning touch exists — see the grace-expiry warning.',
  },
  'grace-expiry-warning': {
    group: 'billing', title: 'Grace-expiry warning', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-grace-expiry-warnings.timer → make grace-expiry-warnings YES=1',
    when: '≤24h before the payment-recovery grace window closes AND ≥12h after it opened. Swept every 4 hours.',
    cadence: 'Timer: 00/4:35 UTC (every 4h, +0–5m jitter)',
    cohort: "subscription_status='past_due', grace window open, not already warned for THIS window, not cancelled, not deleted",
    latch: 'payment_grace_warning_sent_for — stores the window anchor, so a re-opened window re-arms it',
    optOut: 'None (urgent billing)', foh: false,
    source: 'core/mailer.ts:1702 · core/graceExpiryWarning.ts (LEAD 24h / MIN_OPEN 12h)',
    notes: 'A sweeper, not a webhook: no Stripe event fires at "24h before the window closes". The --dry-run window-elapsed counter is an alarm — anything above zero is a member who dropped to Public with no heads-up.',
  },
  'payment-recovered': {
    group: 'billing', title: 'Payment recovered', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'subscription sync past_due → active → maybeHandlePaymentRecovery',
    when: 'Seconds after a failed payment finally clears.',
    cadence: 'Once per failure→recovery cycle',
    cohort: 'payment_recovery_pending = 1, CAS-consumed on the sync back to active.',
    latch: 'payment_recovery_pending flag (CAS 1→0)',
    optOut: 'None (transactional)', foh: true,
    source: 'core/mailer.ts:1996 · app/api/webhooks/stripe/route.ts:1083',
    notes: 'Only fires after a real failure — never on an ordinary renewal.',
  },
  'card-expiring': {
    group: 'billing', title: 'Card expiring', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-card-expiry.timer → make card-expiry-reminders YES=1',
    when: 'When the card on file expires within 45 days and has not already been warned this calendar month. Checked daily.',
    cadence: 'Timer: daily 04:20 UTC (+0–10m jitter)',
    cohort: "subscription_status='active' AND stripe_subscription_id IS NOT NULL AND stripe_customer_id IS NOT NULL AND deleted_at IS NULL, then card expiry resolved live from Stripe",
    latch: 'card_expiry_notified_ym — year-month stamp, so it can warn again in a later month',
    optOut: 'None (billing)', foh: false,
    source: 'core/mailer.ts:1390 · scripts/send-card-expiry-reminders.mts (THRESHOLD 45d, LIMIT 500/run)',
  },
  'referral-reward': {
    group: 'billing', title: 'Referral reward', channel: 'member', autoSends: true,
    trigger: 'App event', triggerDetail: 'core/referrals.ts — referral ledger pending → rewarded',
    when: 'At the moment the referral is credited (the referee\'s subscription qualifies).',
    cadence: 'Once per referral (UNIQUE referee_user_id)',
    cohort: 'Referrer of a qualifying new subscription.',
    latch: 'referrals ledger row state',
    optOut: 'None (account credit notice)', foh: true,
    source: 'core/mailer.ts:323 · core/referrals.ts:354',
  },

  // --------------------------------------------------------------- nudge ----
  'checkout-recovery': {
    group: 'nudge', title: 'Abandoned-checkout recovery', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-checkout-recovery.timer → make checkout-recovery YES=1',
    when: '24–168 hours after a billing_checkout_started audit row with no subscription to show for it. Swept every 6 hours.',
    cadence: 'Timer: 00/6:45 UTC (every 6h, +0–5m jitter)',
    cohort: "audit type='billing_checkout_started' in [now-168h, now-24h] AND stripe_subscription_id IS NULL AND checkout_recovery_email_sent_at IS NULL AND email_verified_at IS NOT NULL AND tier != 'admin' AND deleted_at IS NULL",
    latch: 'checkout_recovery_email_sent_at — permanent one-shot',
    optOut: 'None wired', foh: false,
    source: 'core/mailer.ts:1185 · scripts/send-checkout-recovery.mts (LAG 24h / LOOKBACK 7d)',
    notes: 'Subject has three variants; a live founding deadline outranks a live promo deadline, which outranks the plain version.',
  },
  'verified-never-paid': {
    group: 'nudge', title: 'Verified, never paid', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-verified-never-paid.timer → make verified-never-paid YES=1',
    when: '2–168 hours after verifying, if checkout was never opened. Swept every 2 hours.',
    cadence: 'Timer: 00/2:30 UTC (every 2h, +0–5m jitter)',
    cohort: "tier='public' AND email_verified_at IS NOT NULL AND subscription_lapsed != 1 AND stripe_subscription_id IS NULL AND verified_never_paid_email_sent_at IS NULL AND deleted_at IS NULL AND created_at within [now-168h, now-2h]",
    latch: 'verified_never_paid_email_sent_at — permanent one-shot',
    optOut: 'None wired', foh: false,
    source: 'core/mailer.ts:2557 · scripts/send-verified-never-paid.mts',
    notes: 'Pitches the standard 7-day trial. No discount.',
  },
  'reactivation': {
    group: 'nudge', title: 'Reactivation (extended trial)', channel: 'member', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-reactivation.timer → make reactivation YES=1',
    when: '21+ days after signing up, for a verified account that never started a trial. Checked daily. Max 50 per run.',
    cadence: 'Timer: daily 16:40 UTC (+0–5m jitter)',
    cohort: "tier='public' AND email_verified_at IS NOT NULL AND subscription_lapsed != 1 AND stripe_subscription_id IS NULL AND reactivation_email_sent_at IS NULL AND marketing_unsubscribed_at IS NULL AND created_at older than 21d",
    latch: 'reactivation_email_sent_at — permanent one-shot',
    optOut: 'Honors marketing_unsubscribed_at; RFC 8058 List-Unsubscribe + visible footer', foh: false,
    source: 'core/mailer.ts:2705 · scripts/send-reactivation.mts (LAG 21d, LIMIT 50)',
    notes: 'The offer is a LONGER trial (30 days, granted server-side at ?reactivate=1), never a discount. This one DOES auto-send — unlike win-back and return-intent.',
  },
  'founding-final-call': {
    group: 'nudge', title: 'Founding final call', channel: 'member', autoSends: false,
    trigger: 'Manual', triggerDetail: 'make founding-final-call — no timer',
    when: 'Never automatically. Run by hand the day before the founding deadline.',
    cadence: 'Manual only',
    cohort: 'Operator-selected cohort for the founding deadline.',
    latch: 'founding_final_call_email_sent_at — permanent one-shot',
    optOut: 'n/a', foh: false,
    source: 'core/mailer.ts:1043 · scripts/send-founding-final-call.mts',
    notes: 'Included for completeness: Makefile target exists, no systemd timer does.',
  },

  // --------------------------------------------------------------- churn ----
  'cancellation-ack': {
    group: 'churn', title: 'Cancellation acknowledgment', channel: 'member', autoSends: true,
    trigger: 'Stripe webhook', triggerDetail: 'subscription sync → cancel_at_period_end false→true → maybeHandleCancelAckTransition',
    when: 'Seconds after the member clicks Cancel — while they still have access through period end.',
    cadence: 'Once per cancellation (re-arms if they reactivate then cancel again)',
    cohort: 'cancel_at_period_end flipped to true.',
    latch: 'cancel_ack_email_sent_at — cleared on reactivation',
    optOut: 'None (transactional)', foh: false,
    source: 'core/mailer.ts:2073 · app/api/webhooks/stripe/route.ts:1006',
    notes: 'Carries the signed one-click /save link — 25% off for a year, self-serve, no operator.',
  },
  'winback': {
    group: 'churn', title: 'Win-back', channel: 'member', autoSends: false,
    trigger: 'systemd timer (DIGEST ONLY)', triggerDetail: 'zerogex-web-winback.timer → make winback DIGEST=1',
    when: 'The timer runs weekly, Mondays 16:35 UTC — but it only mails the OPERATOR a review digest. No member is mailed until someone runs make winback YES=1 by hand.',
    cadence: 'Timer: Mon 16:35 UTC (+0–5m jitter) — review only',
    cohort: "subscription_lapsed=1 AND stripe_subscription_id IS NULL AND email_verified_at IS NOT NULL AND tier != 'admin' AND winback_email_sent_at IS NULL AND deleted_at IS NULL AND lapsed 30+ days ago",
    latch: 'winback_email_sent_at — cleared on welcome-back',
    optOut: 'Honors marketing_unsubscribed_at; plain-language opt-out footer', foh: false,
    source: 'core/mailer.ts:2353 · scripts/send-winback.mts (LAG 30d)',
    notes: 'HUMAN IN THE LOOP. The installed unit passes DIGEST=1, not YES=1.',
  },
  'return-intent': {
    group: 'churn', title: 'Return intent', channel: 'member', autoSends: false,
    trigger: 'systemd timer (DIGEST ONLY)', triggerDetail: 'zerogex-web-return-intent.timer → make return-intent DIGEST=1',
    when: 'The timer runs daily at 16:50 UTC — but it only mails the OPERATOR a review digest. No member is mailed until someone runs make return-intent YES=1 by hand.',
    cadence: 'Timer: daily 16:50 UTC (+0–5m jitter) — review only',
    cohort: 'Lapsed, verified, not deleted, not unsubscribed, non-admin, and a login_success AFTER their most recent stripe_subscription_deleted that is between 24h and 14 days old. Cooldown 90 days.',
    latch: 'return_intent_email_sent_at — a COOLDOWN anchor, not a one-shot: it re-arms',
    optOut: 'Honors marketing_unsubscribed_at; RFC 8058 List-Unsubscribe + visible footer', foh: false,
    source: 'core/mailer.ts:3271 · core/returnIntent.ts (QUIET 24h / MAX_AGE 14d / COOLDOWN 90d)',
    notes: 'HUMAN IN THE LOOP. The only churn touch that fires on behaviour (they came back on their own) rather than a calendar. Carries no discount by design.',
  },

  // ------------------------------------------------------------- product ----
  'tradeworkz-alert': {
    group: 'product', title: 'TradeWorkz bot alert', channel: 'member', autoSends: true,
    trigger: 'Queue drain', triggerDetail: 'zerogex-web-tradeworkz-notify.timer → make tradeworkz-notify',
    when: 'Within ~60 seconds of the bot event. The timer drains the queue every minute.',
    cadence: 'Timer: every minute at :12s (+0–15s jitter)',
    cohort: "Queued rows in tw_notifications_log with channel='email' — one send per row.",
    latch: 'tw_notifications_log row state',
    optOut: 'Unfollow the bot from the dashboard', foh: false,
    source: 'core/mailer.ts:2960 · scripts/tradeworkz-notify-deliver.mts',
    notes: 'The only high-frequency member email in the system. Volume tracks bot activity, not the member lifecycle.',
  },

  // ------------------------------------------------------------ operator ----
  'cancellation-alert': {
    group: 'operator', title: 'Cancellation alert', channel: 'operator', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-cancellation-alerts.timer → make cancellation-alerts',
    when: 'Within 15 minutes of a churn event. Swept at :07, :22, :37, :52 past every hour.',
    cadence: 'Timer: every 15 min (+0–45s jitter)',
    cohort: "audit_events of type stripe_cancellation_requested (still has access) or stripe_subscription_deleted (access gone)",
    latch: 'cancellation_alert_sent audit row keyed to the churn event id',
    optOut: 'n/a — internal', foh: false,
    source: 'core/mailer.ts:2383 · scripts/send-cancellation-alerts.mts',
    notes: 'Sends nothing to the member. Carries the Stripe cancellation survey verbatim plus pre-filled make commands.',
  },
  'winback-digest': {
    group: 'operator', title: 'Win-back review digest', channel: 'operator', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-winback.timer → make winback DIGEST=1',
    when: 'Weekly, Mondays 16:35 UTC.',
    cadence: 'Timer: Mon 16:35 UTC (+0–5m jitter)',
    cohort: 'One digest listing everyone the win-back email WOULD go to.',
    latch: 'n/a',
    optOut: 'n/a — internal', foh: false,
    source: 'core/mailer.ts:2483 · scripts/send-winback.mts',
    notes: 'Embeds the real rendered member draft so the reviewer sees exactly what would ship.',
  },
  'reactivation-digest': {
    group: 'operator', title: 'Reactivation review digest', channel: 'operator', autoSends: false,
    trigger: 'Manual', triggerDetail: 'make reactivation DIGEST=1 — the installed timer passes YES=1, not DIGEST=1',
    when: 'Never automatically. --digest is an exclusive branch that exits before sending, and the unit does not pass it.',
    cadence: 'Manual only',
    cohort: 'One digest listing the cold signups in scope.',
    latch: 'n/a',
    optOut: 'n/a — internal', foh: false,
    source: 'core/mailer.ts:2732 · scripts/send-reactivation.mts:446',
    notes: 'Asymmetry worth knowing: win-back and return-intent ship as digest-only, reactivation ships as live-send-only. Nobody reviews the reactivation batch before it goes out.',
  },
  'return-intent-digest': {
    group: 'operator', title: 'Return-intent review digest', channel: 'operator', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-return-intent.timer → make return-intent DIGEST=1',
    when: 'Daily at 16:50 UTC.',
    cadence: 'Timer: daily 16:50 UTC (+0–5m jitter)',
    cohort: 'One digest per returning-member batch, with each member\'s angle.',
    latch: 'n/a',
    optOut: 'n/a — internal', foh: false,
    source: 'core/mailer.ts:3300 · scripts/send-return-intent.mts',
  },
  'unit-failure-alert': {
    group: 'operator', title: 'Scheduled-unit failure alert', channel: 'operator', autoSends: true,
    trigger: 'systemd OnFailure', triggerDetail: 'OnFailure=zerogex-web-alert@%n.service on every scheduled unit',
    when: 'The instant any scheduled unit exits non-zero. Not a schedule — a failure hook.',
    cadence: 'Event-driven',
    cohort: 'Any failing zerogex-web-* unit.',
    latch: 'None — every failure alerts',
    optOut: 'n/a — internal', foh: false,
    source: 'scripts/send-unit-failure-alert.mts · deploy/systemd/zerogex-web-alert@.service',
    notes: 'This is the email that tells you the other emails stopped sending. Carries the last N journal lines. In the render below the journal excerpt is empty and systemctl errors — the capture ran outside systemd, so there was no journal to read. On the box those blocks carry the real failure output.',
  },
  'signup-alarm': {
    group: 'operator', title: 'Signup-rate alarm', channel: 'operator', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-signup-alarm.timer → make signup-alarm',
    when: 'Hourly at :35 UTC. The script itself gates to active hours and only alerts when the signup rate drops below the floor.',
    cadence: 'Timer: hourly :35 (+0–3m jitter)',
    cohort: 'Counts users.created_at over a rolling window.',
    latch: 'In-script rate gate',
    optOut: 'n/a — internal', foh: false,
    source: 'scripts/send-signup-alarm.mts',
  },
  'foh-donation-reminder': {
    group: 'operator', title: 'Folds of Honor donation reminder', channel: 'operator', autoSends: true,
    trigger: 'systemd timer', triggerDetail: 'zerogex-web-foh-donation-reminder.timer → make foh-donation-reminder',
    when: 'Quarterly — the 5th of January, April, July and October at 09:00 ET.',
    cadence: 'Timer: 5th of Jan/Apr/Jul/Oct, 09:00 ET (+0–10m jitter)',
    cohort: 'n/a — one reminder to the operator.',
    latch: 'n/a',
    optOut: 'n/a — internal', foh: false,
    source: 'scripts/send-foh-donation-reminder.mts',
    notes: 'One of only two units pinned to America/New_York rather than server time.',
  },
};

// Everything that can send mail but is NOT wired to fire on its own.
export const MANUAL = [
  { name: 'Product-update newsletter', cmd: 'make send-product-update', what: 'Founder-voice broadcast; copy lives in docs/newsletters/2026-07-product-update.{html,txt}. Honors marketing_unsubscribed_at, invisible List-Unsubscribe header.' },
  { name: 'Founding final call', cmd: 'make founding-final-call', what: 'Deadline-day urgency closer. Latched per account.' },
  { name: 'Trial quickstart bridge', cmd: 'make send-trial-quickstart', what: 'One-shot backfill for members mid-trial before the new welcome shipped.' },
  { name: 'Welcome email (re-send)', cmd: 'make send-welcome-email', what: 'Operator re-send of the paid / founding / welcome-back email.' },
  { name: 'Payment-failed preview', cmd: 'make payment-failed-preview', what: 'Renders the dunning email to a chosen address. Testing aid.' },
  { name: 'Payment-recovered (manual)', cmd: 'scripts/send-payment-recovered.mts', what: 'Operator re-send of the recovery bookend.' },
  { name: 'Trial back-credit', cmd: 'scripts/back-credit-trial.mts', what: 'One-off: notified pre-trial monthly subscribers of a ~7/31-month credit. Inline HTML, not mailer.ts.' },
  { name: 'Founding July-1 delay credit', cmd: 'scripts/credit-founders-july1-delay.mts', what: 'One-off: notified founders of a one-month credit at the founding rate. Inline HTML, not mailer.ts.' },
  { name: 'API 403 incident notice', cmd: 'make send-403-notice', what: 'One-off incident notice to affected API users.' },
  { name: 'Quarterly Folds of Honor receipt', cmd: 'make quarterly-receipt', what: 'Interactive publish loop; optional EMAIL= mails the tweet draft to the operator.' },
];
