import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import {
  SIERRACHART_STUDY_HASH,
  SIERRACHART_STUDY_PATH,
  THINKORSWIM_STUDY_HASH,
  THINKORSWIM_STUDY_PATH,
} from '../core/integrationAssets.ts';

// core/integrationAssets.ts is generated by scripts/integration-assets-manifest.js
// but COMMITTED, so that a plain `npm run build` needs no pre-step. That is the
// convenience this suite pays for: a committed generated file drifts silently
// from the sources it was generated from, and nothing about the pages that read
// it looks wrong when it does.
//
// The failure it drifts into is specific and invisible from the page. The
// generator only ever writes the CURRENT hash into public/, so a stale manifest
// names a URL no deploy has written — and the download button, whose href is a
// build-time constant, is checked by nothing at render time and nothing at
// request time either. The customer gets a 404 from a button that looks
// completely normal. That exact bug has already happened once with the
// NinjaTrader indicator; see tests/ninjaTraderManifest.test.ts, which this
// mirrors for the other two study sources.
//
// These assertions are what `node scripts/integration-assets-manifest.js --check`
// proves at deploy time, restated where a developer will hit them first.

const HERE = path.dirname(new URL(import.meta.url).pathname);

/** Same digest the generator uses: first 8 hex of the file's sha256. */
function hashOf(relativeToPublic: string): string {
  const file = path.join(HERE, '../public', relativeToPublic);
  return createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 8);
}

const STALE =
  'is stale: the study changed without a regenerate, so the page links a hashed ' +
  'URL no deploy will ever write (a 404 for the customer). Run `make integration-assets` ' +
  'and commit the result.';

test('the committed thinkorswim hash matches the tracked study', () => {
  assert.equal(
    THINKORSWIM_STUDY_HASH,
    hashOf('thinkorswim/zerogex-daily-gamma-levels.thinkscript'),
    `integrationAssets.ts ${STALE}`,
  );
});

test('the committed Sierra Chart hash matches the tracked study', () => {
  assert.equal(
    SIERRACHART_STUDY_HASH,
    hashOf('sierrachart/ZeroGexGammaLevels.cpp'),
    `integrationAssets.ts ${STALE}`,
  );
});

test('each path is the one derived from its own hash', () => {
  // Path and hash are written from the same variable by the generator, so they
  // can only disagree if someone hand-edited the file it says not to hand-edit.
  assert.equal(
    THINKORSWIM_STUDY_PATH,
    `/thinkorswim/zerogex-daily-gamma-levels.${THINKORSWIM_STUDY_HASH}.thinkscript`,
  );
  assert.equal(
    SIERRACHART_STUDY_PATH,
    `/sierrachart/ZeroGexGammaLevels.${SIERRACHART_STUDY_HASH}.cpp`,
  );
});

test('the thinkorswim study is not stored with a .ts extension', () => {
  // frontend/tsconfig.json globs every .ts file with only node_modules
  // excluded, so a thinkScript file saved under public/ with the extension
  // thinkorswim itself uses would be handed to the TypeScript compiler and
  // fail the build. The .thinkscript extension is load-bearing, and the
  // download button restores the .ts name via its `download` attribute.
  assert.ok(THINKORSWIM_STUDY_PATH.endsWith('.thinkscript'));
});
