import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import {
  NT_INDICATOR_HASH,
  NT_INDICATOR_PATH,
  NT_PACKAGE_HASH,
  NT_PACKAGE_PATH,
} from '../core/ninjaTraderManifest.ts';

// core/ninjaTraderManifest.ts is generated by scripts/ninjatrader-manifest.js
// but COMMITTED, so that a plain `npm run build` needs no pre-step. That is the
// convenience this suite pays for: a committed generated file drifts silently
// from the sources it was generated from, and nothing about the page that reads
// it looks wrong when it does.
//
// It drifted once already. The indicator .cs was edited and committed without
// re-running `make ninjatrader-package`, so the manifest kept advertising the
// PREVIOUS build's content hash. The download button on every gamma-levels page
// then pointed at /ninjatrader/ZeroGexGammaLevels.<old-hash>.cs — a file no
// deploy had ever written, because the generator only ever emits the CURRENT
// hash. Customers got a 404 from a button that looked completely normal, and
// the page had no way to know: the URL is a build-time constant, so nothing
// checks it at render time and nothing checks it at request time either.
//
// These assertions are what `node scripts/ninjatrader-manifest.js --check`
// proves at deploy time, restated where a developer will hit them first.

const HERE = path.dirname(new URL(import.meta.url).pathname);
const INDICATOR_CS = path.join(HERE, '../public/ninjatrader/ZeroGexGammaLevels.cs');

// Widened from the literal types the generator emits. The manifest legitimately
// flips between a path and null as the export archive comes and goes, and this
// file must compile either way.
const packageHash: string | null = NT_PACKAGE_HASH;
const packagePath: string | null = NT_PACKAGE_PATH;

/** Same digest the generator uses: first 8 hex of the file's sha256. */
function hashOf(file: string): string {
  return createHash('sha256').update(readFileSync(file)).digest('hex').slice(0, 8);
}

test('the committed indicator hash matches the tracked .cs', () => {
  assert.equal(
    NT_INDICATOR_HASH,
    hashOf(INDICATOR_CS),
    'ninjaTraderManifest.ts is stale: the indicator changed without a regenerate. ' +
      'The download button is pointing at a hashed URL no deploy will ever write ' +
      '(a 404 for the customer). Run `make ninjatrader-package` and commit the result.',
  );
});

test('the indicator path is the one derived from the indicator hash', () => {
  // Path and hash are written from the same variable by the generator, so they
  // can only disagree if someone hand-edited the file it says not to hand-edit.
  assert.equal(NT_INDICATOR_PATH, `/ninjatrader/ZeroGexGammaLevels.${NT_INDICATOR_HASH}.cs`);
});

test('the package hash and path are either both absent or both present', () => {
  // The page turns a non-null NT_PACKAGE_PATH into a live "Download for
  // NinjaTrader" button, so a half-populated pair is a rendered link to
  // nothing. Absent is a supported state (the pages offer the .cs alone);
  // half-absent is not.
  assert.equal(
    packageHash === null,
    packagePath === null,
    'NT_PACKAGE_HASH and NT_PACKAGE_PATH disagree about whether an archive is published',
  );
});

test('a published package path embeds its own hash', () => {
  if (packagePath === null) return; // No archive published — nothing to check.
  assert.equal(packagePath, `/ninjatrader/ZeroGexGammaLevels.${packageHash}.zip`);
});
