// GENERATED by scripts/integration-assets-manifest.js — do not edit by hand.
//
// Re-run `make integration-assets` after editing any chart-platform study
// source, and commit the result. The hash is what makes a new build actually
// reach people instead of being answered from a Cloudflare edge still holding
// the previous bytes — see the header comment in that script.

/** Content hash of the thinkScript study source (manual-entry) (first 8 hex of its sha256). */
export const THINKORSWIM_STUDY_HASH = 'a490a64e';

/** Cache-busting path for the thinkScript study source (manual-entry), relative to the site root. */
export const THINKORSWIM_STUDY_PATH = '/thinkorswim/zerogex-daily-gamma-levels.a490a64e.thinkscript';

/** Content hash of the Sierra Chart ACSIL study source (auto-updating) (first 8 hex of its sha256). */
export const SIERRACHART_STUDY_HASH = '52018a6c';

/** Cache-busting path for the Sierra Chart ACSIL study source (auto-updating), relative to the site root. */
export const SIERRACHART_STUDY_PATH = '/sierrachart/ZeroGexGammaLevels.52018a6c.cpp';
