// GENERATED by scripts/ninjatrader-manifest.js — do not edit by hand.
//
// Re-run `make ninjatrader-package` after changing the indicator or replacing
// the export archive, and commit the result. The hash is what makes a new build
// actually reach customers instead of being answered from a Cloudflare edge
// still holding the previous bytes — see the header comment in that script.

/** Content hash of the indicator source (first 8 hex of its sha256). */
export const NT_INDICATOR_HASH = '42240948';

/** Cache-busting path for the indicator source, relative to the site root. */
export const NT_INDICATOR_PATH = '/ninjatrader/ZeroGexGammaLevels.42240948.cs';

/** Content hash of the packaged NinjaTrader export, or null when none is published. */
export const NT_PACKAGE_HASH = null;

/** Cache-busting path for the packaged export, or null when none is published. */
export const NT_PACKAGE_PATH = null;
