// GENERATED by scripts/og-image-manifest.js — do not edit by hand.
//
// Re-run `make logo` (or `node scripts/og-image-manifest.js`) after replacing
// assets/branding/og-image.png, and commit the result. The hash is what makes a
// new social card actually reach X/LinkedIn/Facebook instead of being answered
// from a Cloudflare edge or a scraper's card cache that still holds the old
// bytes — see the header comment in that script for the full story.

/** Content hash of assets/branding/og-image.png (first 8 hex of its sha256). */
export const OG_IMAGE_HASH = 'f65afa1b';

/** Cache-busting path for the site-wide social card, relative to the site root. */
export const OG_IMAGE_PATH = '/og-image.f65afa1b.png';

/** The card's real pixel dimensions, read from the PNG's IHDR chunk. */
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;
